### ISSUE TITLE
FR: sync directory

### ISSUE THREAD

**Issue by utdrmac** [tbumi/glacier-upload#20]
Any plans to support sync of entire directory to a vault? Looking to use a native Glacier client as backup tool but need recursive/directory/sync support.

**Comment by tbumi** [comment]
First of all, sorry for the late reply.

As for uploading entire directories, the `glacier_upload` command supports using a directory for its `--file-name` argument. The directory will automatically be archived into a single tar file before being uploaded to a vault.

If you mean synchronizing the contents of a directory to an archive in a vault (and only uploading changes/diffs), that is currently impossible, because glacier only supports uploading single archive files. Consider using S3 as an alternative for that use case.
